"""接口自动化用例元数据。"""

API_TEST_CASES = [
  {
    "id": "TC-API-LOGIN-001",
    "title": "登录接口-账号字段SQL注入防护",
    "class": "TestLoginApiSqlInjection",
    "method": "test_sql_injection_in_user_name_rejected",
    "module": "登录接口",
    "story": "SQL注入防护",
    "priority": "P0",
    "type": "安全测试",
    "precondition": "1. 可访问 passport 服务\n2. 已 warm_session 获取 Cookie",
    "steps": "1. POST /api/v1/login\n2. user_name 填入 SQL 注入 payload\n3. password 为普通字符串（MD5）\n4. captcha 为空",
    "expected": "1. 登录不成功\n2. 响应无 SQL 错误泄露\n3. 不返回 5xx",
    "data": "payload 见 utils/sql_injection_payloads.py",
    "remark": "参数化",
  },
  {
    "id": "TC-API-LOGIN-002",
    "title": "登录接口-密码字段SQL注入防护（明文传入）",
    "class": "TestLoginApiSqlInjection",
    "method": "test_sql_injection_in_password_plain_rejected",
    "module": "登录接口",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "同 TC-API-LOGIN-001",
    "steps": "1. user_name 为普通字符串\n2. password 填入 SQL payload（不做 MD5）\n3. 提交登录",
    "expected": "同 TC-API-LOGIN-001",
    "data": "payload 见 PASSWORD_PAYLOADS",
    "remark": "探测服务端是否错误拼接密码",
  },
  {
    "id": "TC-API-LOGIN-003",
    "title": "登录接口-密码字段SQL注入防护（MD5后传入）",
    "class": "TestLoginApiSqlInjection",
    "method": "test_sql_injection_in_password_hashed_rejected",
    "module": "登录接口",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "同 TC-API-LOGIN-001",
    "steps": "1. user_name 为普通字符串\n2. password 为 SQL payload，按接口规则 MD5 后提交",
    "expected": "同 TC-API-LOGIN-001",
    "data": "payload 见 PASSWORD_PAYLOADS",
    "remark": "",
  },
  {
    "id": "TC-API-LOGIN-004",
    "title": "登录接口-双字段SQL注入防护",
    "class": "TestLoginApiSqlInjection",
    "method": "test_sql_injection_in_both_fields_rejected",
    "module": "登录接口",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "同 TC-API-LOGIN-001",
    "steps": "1. user_name、password 均填入 SQL payload\n2. 提交登录",
    "expected": "同 TC-API-LOGIN-001",
    "data": "payload 见 ACCOUNT_PAYLOADS",
    "remark": "",
  },
  {
    "id": "TC-SESSION-007",
    "title": "未登录访问受保护接口-应拒绝",
    "class": "TestSessionApi",
    "method": "test_protected_api_rejects_without_session",
    "module": "会话与状态",
    "story": "路由与门禁",
    "priority": "P0",
    "type": "接口自动化",
    "precondition": "1. 已配置 API_CURRENT_USER_PATH 或 API_LIST_PATH",
    "steps": "1. 使用无 Cookie 的 client\n2. GET 受保护接口",
    "expected": "1. 返回 401/403 或业务未登录错误码",
    "data": "接口路径见 .env（API_CURRENT_USER_PATH / API_LIST_PATH）",
    "remark": "接口层子集",
  },
  {
    "id": "TC-SESSION-014",
    "title": "current-user与列表接口归属一致",
    "class": "TestSessionApi",
    "method": "test_current_user_matches_list_api",
    "module": "会话与状态",
    "story": "接口一致性",
    "priority": "P0",
    "type": "接口自动化",
    "precondition": "1. .env 已配置 SESSION_COOKIE_B\n2. 已配置 API_CURRENT_USER_PATH、API_LIST_PATH",
    "steps": "1. 注入 B 的 Cookie\n2. GET current-user\n3. GET 列表接口\n4. 比对账号标识",
    "expected": "1. 两个接口均成功\n2. 账号标识一致",
    "data": "SESSION_ACCOUNT_B、SESSION_COOKIE_B、API_CURRENT_USER_PATH、API_LIST_PATH",
    "remark": "",
  },
]

API_CASE_BY_ID = {case["id"]: case for case in API_TEST_CASES}


def api_allure_display_title(case: dict) -> str:
  return f"{case['id']} {case['title']}"
