"""会话与状态一致性 — 手工测试用例元数据（用于 Excel 导出）。"""

SESSION_TEST_CASES = [
  {
    "id": "TC-SESSION-001",
    "title": "同浏览器先后登录A再登录B-展示与数据一致",
    "module": "会话与状态",
    "story": "账号切换",
    "priority": "P0",
    "type": "手工测试",
    "precondition": "1. 准备两个可登录测试账号 A、B（均有业务数据）\n2. 使用 Chrome 正常模式\n3. 建议打开 F12（Network + Application）",
    "steps": "1. 账号 A 登录并进入首页/任意业务列表\n2. 记录右上角账号信息与列表关键字段（如网吧名/ID）\n3. 不关闭浏览器，退出登录（若无退出则清 Cookie 后重开登录页）\n4. 账号 B 登录并进入同一业务页\n5. 对比右上角与列表/详情数据",
    "expected": "1. 右上角展示账号为 B\n2. 列表/详情数据归属 B，不出现 A 的数据\n3. 不应出现「数据是 B、右上角仍是 A」",
    "data": "账号 A：____\n账号 B：____",
    "method": "手工",
    "remark": "对应已发现的前端状态残留问题",
  },
  {
    "id": "TC-SESSION-002",
    "title": "账号切换后-前端存储与鉴权一致",
    "module": "会话与状态",
    "story": "账号切换",
    "priority": "P0",
    "type": "手工测试",
    "precondition": "1. 已完成 TC-SESSION-001 步骤 4（当前为 B 登录态）\n2. F12 → Application 已打开",
    "steps": "1. 查看 Cookies（passport 域）中与登录相关的项\n2. 查看 localStorage / sessionStorage 中 userInfo、userName、token 等 key\n3. 在 Network 中找 current-user / profile / me 类接口响应\n4. 对比：存储中的账号标识 vs 接口返回 vs 右上角展示",
    "expected": "1. Cookie/token、localStorage 用户标识、接口返回、页面展示四者一致，均为 B\n2. 不应残留 A 的 userName/userInfo",
    "data": "记录不一致的 key 名称：____",
    "method": "手工",
    "remark": "用于定位状态写在哪一层",
  },
  {
    "id": "TC-SESSION-003",
    "title": "先登出再登录B-无A账号残留",
    "module": "会话与状态",
    "story": "登出与重登",
    "priority": "P0",
    "type": "手工测试",
    "precondition": "1. 账号 A 已登录",
    "steps": "1. 点击退出登录\n2. 确认回到登录页\n3. 账号 B 登录\n4. 检查右上角、业务数据、Application 存储",
    "expected": "1. 全流程无 A 的展示或数据残留\n2. 若产品要求「登出清态」，localStorage 中不应有 A 信息",
    "data": "账号 A：____  账号 B：____",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-004",
    "title": "登录后刷新页面-用户信息不错乱",
    "module": "会话与状态",
    "story": "页面刷新",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 B 已登录并在业务页",
    "steps": "1. 记录右上角账号与当前页一条业务数据\n2. F5 刷新页面\n3. 再次对比右上角与业务数据",
    "expected": "1. 刷新后仍为 B\n2. 右上角与数据一致，无跳变、无空白、无回退到 A",
    "data": "无",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-005",
    "title": "双标签页-不同账号登录互相影响",
    "module": "会话与状态",
    "story": "多标签页",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 同一浏览器两个 Tab 打开系统",
    "steps": "1. Tab1：账号 A 登录并打开列表页\n2. Tab2：打开登录页，账号 B 登录\n3. 回到 Tab1 刷新或点击菜单进入列表\n4. 观察 Tab1 右上角与数据",
    "expected": "1. 应有明确规则：要么 Tab1 同步为 B，要么提示重新登录\n2. 不允许 Tab1 静默展示 A 但数据已是 B（或反之）",
    "data": "账号 A：____  账号 B：____",
    "method": "手工",
    "remark": "多 Tab 是高频踩坑场景",
  },
  {
    "id": "TC-SESSION-006",
    "title": "已登录状态访问登录页",
    "module": "会话与状态",
    "story": "路由与门禁",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 A 已登录",
    "steps": "1. 地址栏直接访问 /account/login\n2. 观察是否跳转、是否提示、是否可重复登录",
    "expected": "1. 应跳转首页/工作台，或提示「已登录」\n2. 不应在已登录态下叠一层登录导致状态混乱",
    "data": "无",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-007",
    "title": "未登录直链访问内页",
    "module": "会话与状态",
    "story": "路由与门禁",
    "priority": "P0",
    "type": "手工测试",
    "precondition": "1. 浏览器无痕/已清 Cookie\n2. 未登录",
    "steps": "1. 直接访问业务内页 URL（收藏夹或手工输入）\n2. 观察跳转与提示",
    "expected": "1. 应跳转登录页\n2. 不应短暂展示他人数据或空白敏感页",
    "data": "内页 URL：____",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-008",
    "title": "登出后浏览器后退",
    "module": "会话与状态",
    "story": "登出与重登",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 A 已登录并浏览过多页",
    "steps": "1. 退出登录\n2. 点击浏览器「后退」多次\n3. 尝试查看是否仍能看到业务数据或操作按钮",
    "expected": "1. 后退不应恢复有效业务操作\n2. 应跳转登录或提示重新登录\n3. 敏感数据不应从缓存页直接可见",
    "data": "无",
    "method": "手工",
    "remark": "bfcache 场景",
  },
  {
    "id": "TC-SESSION-009",
    "title": "篡改localStorage用户名-一致性校验（期望）",
    "module": "会话与状态",
    "story": "一致性兜底",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 B 已登录\n2. 了解 Application → localStorage",
    "steps": "1. 在 localStorage 将 userName/userInfo 改成 A 的账号（仅改展示用字段，不动 token）\n2. 刷新或切换菜单\n3. 观察是否提示异常并要求重新登录",
    "expected": "1. 【期望】检测到展示与鉴权不一致\n2. 弹窗提示「请重新登录」并清空状态\n3. 若当前无此能力，记为缺陷",
    "data": "篡改 key：____",
    "method": "手工",
    "remark": "验证一致性兜底方案是否已实现",
  },
  {
    "id": "TC-SESSION-010",
    "title": "仅清除Cookie保留localStorage",
    "module": "会话与状态",
    "story": "异常状态恢复",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 B 已登录",
    "steps": "1. F12 删除全部 Cookie（保留 localStorage）\n2. 刷新页面或访问业务接口\n3. 观察页面表现",
    "expected": "1. 应识别未登录/会话失效\n2. 跳转登录或统一错误提示\n3. 不应半登录态继续使用",
    "data": "无",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-011",
    "title": "同账号连续登录两次",
    "module": "会话与状态",
    "story": "重复登录",
    "priority": "P2",
    "type": "手工测试",
    "precondition": "1. 账号 A 可用",
    "steps": "1. A 登录成功进入首页\n2. 再次打开登录页用 A 登录（或重复提交登录）\n3. 检查右上角与业务数据",
    "expected": "1. 无报错、无重复弹窗\n2. 展示与数据仍为 A，状态正常",
    "data": "账号 A：____",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-012",
    "title": "会话过期后操作",
    "module": "会话与状态",
    "story": "会话过期",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 A 已登录\n2. 可等待空闲超时或请后端缩短 session（如有测试环境）",
    "steps": "1. 保持页面打开直至会话过期（或手动删 token）\n2. 点击查询/提交等操作\n3. 观察提示与跳转",
    "expected": "1. 接口 401/403 时前端统一提示重新登录\n2. 清本地状态，不出现脏数据",
    "data": "空闲时长：____ 分钟",
    "method": "手工",
    "remark": "无测试环境可标为阻塞",
  },
  {
    "id": "TC-SESSION-013",
    "title": "跨模块导航-右上角与各页数据同账号",
    "module": "会话与状态",
    "story": "多模块一致",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号 B 已登录\n2. 系统有多个菜单模块",
    "steps": "1. 依次进入 3 个不同业务模块\n2. 每个模块记录一条数据归属与右上角账号\n3. 对比是否一致",
    "expected": "1. 各模块数据均归属 B\n2. 右上角始终为 B",
    "data": "模块列表：____",
    "method": "手工",
    "remark": "",
  },
  {
    "id": "TC-SESSION-014",
    "title": "current-user与列表接口归属一致",
    "module": "会话与状态",
    "story": "接口一致性",
    "priority": "P0",
    "type": "手工测试",
    "precondition": "1. 账号 B 已登录\n2. Network 保留日志",
    "steps": "1. 触发右上角用户信息加载（若无则刷新）\n2. 打开任意列表接口请求\n3. 对比 current-user（或同类）响应中的 userId/account 与列表数据归属",
    "expected": "1. 接口层账号标识一致\n2. 若不一致应触发前端校验或不应静默展示",
    "data": "current-user URL：____",
    "method": "手工",
    "remark": "偏接口+前端联合验证",
  },
  {
    "id": "TC-SESSION-015",
    "title": "登录滑块验证后-状态完整写入",
    "module": "会话与状态",
    "story": "登录完成态",
    "priority": "P1",
    "type": "手工测试",
    "precondition": "1. 账号需滑块验证\n2. 准备有效测试账号",
    "steps": "1. 完成滑块后登录成功\n2. 立即检查右上角、首页数据、Application 存储\n3. 刷新后再检查一次",
    "expected": "1. 登录当次与刷新后状态一致\n2. token、profile、展示三者同步",
    "data": "账号：____",
    "method": "手工",
    "remark": "与正向登录流程相关",
  },
]
