"""测试用例元数据：Excel 导出与 Allure 报告共用。"""

TEST_CASES = [
  {
    "id": "TC-LOGIN-001",
    "title": "登录页核心元素加载校验",
    "class": "TestLoginPageLoad",
    "method": "test_login_page_loads_with_core_elements",
    "module": "登录模块",
    "story": "页面加载",
    "priority": "P0",
    "type": "冒烟测试",
    "precondition": "1. 网络可访问 https://passport.xiongmaozhanggui.com\n2. 浏览器可正常打开",
    "steps": "1. 打开登录页 /account/login\n2. 查看页面标题\n3. 查看当前 URL\n4. 查看网吧账号、密码输入框",
    "expected": "1. 页面标题包含「熊猫掌柜用户管理系统」\n2. URL 包含 /account/login\n3. 显示「请输入网吧账号」输入框\n4. 显示「请输入密码」输入框",
    "data": "无",
    "remark": "冒烟用例",
  },
  {
    "id": "TC-LOGIN-002",
    "title": "登录页辅助入口可见性校验",
    "class": "TestLoginPageLoad",
    "method": "test_auxiliary_links_visible",
    "module": "登录模块",
    "story": "页面加载",
    "priority": "P1",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 打开登录页\n2. 查看「忘记密码」按钮\n3. 查看「注册账号」按钮",
    "expected": "1. 「忘记密码」按钮可见\n2. 「注册账号」按钮可见",
    "data": "无",
    "remark": "冒烟用例",
  },
  {
    "id": "TC-LOGIN-003",
    "title": "网吧登录-账号密码均为空时提交",
    "class": "TestInternetCafeValidation",
    "method": "test_empty_form_shows_required_errors",
    "module": "登录模块",
    "story": "网吧登录-表单校验",
    "priority": "P0",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 不填写任何字段\n2. 点击「登录」按钮",
    "expected": "1. 账号框下方提示「请输入网吧账号」\n2. 密码框下方提示「请输入密码」\n3. 仍停留在登录页",
    "data": "账号：空\n密码：空",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-004",
    "title": "网吧登录-仅填写账号不填密码",
    "class": "TestInternetCafeValidation",
    "method": "test_missing_password_shows_error",
    "module": "登录模块",
    "story": "网吧登录-表单校验",
    "priority": "P1",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 在网吧账号框输入 test_account\n2. 密码框留空\n3. 点击「登录」",
    "expected": "1. 密码框下方提示「请输入密码」\n2. 仍停留在登录页",
    "data": "账号：test_account\n密码：空",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-005",
    "title": "网吧登录-仅填写密码不填账号",
    "class": "TestInternetCafeValidation",
    "method": "test_missing_account_shows_error",
    "module": "登录模块",
    "story": "网吧登录-表单校验",
    "priority": "P1",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 账号框留空\n2. 在密码框输入 test_password\n3. 点击「登录」",
    "expected": "1. 账号框下方提示「请输入网吧账号」\n2. 仍停留在登录页",
    "data": "账号：空\n密码：test_password",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-006",
    "title": "员工登录-Tab 切换后显示三个输入框",
    "class": "TestStaffValidation",
    "method": "test_staff_tab_shows_three_fields",
    "module": "登录模块",
    "story": "员工登录-表单校验",
    "priority": "P1",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 点击「员工登录」Tab\n2. 查看页面输入框",
    "expected": "1. 显示「请输入网吧账号」输入框\n2. 显示「请输入员工账号」输入框\n3. 显示「请输入密码」输入框",
    "data": "无",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-007",
    "title": "员工登录-三个字段均为空时提交",
    "class": "TestStaffValidation",
    "method": "test_empty_form_shows_all_required_errors",
    "module": "登录模块",
    "story": "员工登录-表单校验",
    "priority": "P1",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「员工登录」",
    "steps": "1. 不填写任何字段\n2. 点击「登录」",
    "expected": "1. 提示「请输入网吧账号」\n2. 提示「请输入员工账号」\n3. 提示「请输入密码」\n4. 仍停留在登录页",
    "data": "全部为空",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-008",
    "title": "代理商登录-Tab 切换后显示对应输入框",
    "class": "TestAgentValidation",
    "method": "test_agent_tab_shows_fields",
    "module": "登录模块",
    "story": "代理商登录-表单校验",
    "priority": "P1",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 点击「代理商登录」Tab\n2. 查看页面输入框",
    "expected": "1. 显示「请输入代理商账号」输入框\n2. 显示「请输入密码」输入框",
    "data": "无",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-009",
    "title": "代理商登录-账号密码均为空时提交",
    "class": "TestAgentValidation",
    "method": "test_empty_form_shows_required_errors",
    "module": "登录模块",
    "story": "代理商登录-表单校验",
    "priority": "P1",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「代理商登录」",
    "steps": "1. 不填写任何字段\n2. 点击「登录」",
    "expected": "1. 提示「请输入代理商账号」\n2. 提示「请输入密码」\n3. 仍停留在登录页",
    "data": "全部为空",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-010",
    "title": "三种登录 Tab 切换表单联动校验",
    "class": "TestTabSwitching",
    "method": "test_tabs_switch_form_fields",
    "module": "登录模块",
    "story": "Tab切换",
    "priority": "P1",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 确认默认显示网吧登录表单\n2. 切换到「员工登录」\n3. 切换到「代理商登录」\n4. 切换回「网吧登录」",
    "expected": "1. 网吧登录：网吧账号+密码\n2. 员工登录：网吧账号+员工账号+密码\n3. 代理商登录：代理商账号+密码\n4. 切回网吧登录：恢复网吧账号+密码",
    "data": "无",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-011",
    "title": "网吧登录-错误账号密码登录失败",
    "class": "TestInvalidCredentials",
    "method": "test_wrong_credentials_stays_on_login_page",
    "module": "登录模块",
    "story": "错误凭证",
    "priority": "P1",
    "type": "负向测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 输入错误账号和密码\n2. 点击「登录」",
    "expected": "1. 弹出错误提示\n2. 仍停留在登录页",
    "data": "账号：invalid_test_account_12345\n密码：wrong_password_123",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-012",
    "title": "点击忘记密码跳转找回密码页",
    "class": "TestAuxiliaryActions",
    "method": "test_forgot_password_navigates_to_reset_page",
    "module": "登录模块",
    "story": "辅助入口",
    "priority": "P1",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 点击「忘记密码」",
    "expected": "1. 跳转到找回密码页\n2. 显示手机/邮箱找回入口及「下一步」按钮",
    "data": "无",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-013",
    "title": "点击注册账号弹出停止自主注册提示",
    "class": "TestAuxiliaryActions",
    "method": "test_register_shows_stop_registration_dialog",
    "module": "登录模块",
    "story": "辅助入口",
    "priority": "P2",
    "type": "功能测试",
    "precondition": "1. 已打开登录页",
    "steps": "1. 点击「注册账号」\n2. 查看弹窗\n3. 点击「确定」关闭",
    "expected": "1. 弹出停止自主注册提示\n2. 包含「区域经理」文案\n3. 关闭后仍停留在登录页",
    "data": "无",
    "remark": "",
  },
  {
    "id": "TC-LOGIN-014",
    "title": "网吧登录-账号字段SQL注入防护",
    "class": "TestSqlInjection",
    "method": "test_sql_injection_in_account_field_rejected",
    "module": "登录模块",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 在网吧账号框输入 SQL 注入 payload\n2. 密码输入普通字符串\n3. 点击「登录」",
    "expected": "1. 登录失败，仍停留在登录页\n2. 页面不泄露 SQL/数据库错误信息\n3. 不应绕过鉴权进入系统",
    "data": "payload 见 utils/sql_injection_payloads.py",
    "remark": "参数化多条 payload",
  },
  {
    "id": "TC-LOGIN-015",
    "title": "网吧登录-密码字段SQL注入防护",
    "class": "TestSqlInjection",
    "method": "test_sql_injection_in_password_field_rejected",
    "module": "登录模块",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 网吧账号输入普通字符串\n2. 密码框输入 SQL 注入 payload\n3. 点击「登录」",
    "expected": "1. 登录失败，仍停留在登录页\n2. 页面不泄露 SQL/数据库错误信息",
    "data": "payload 见 utils/sql_injection_payloads.py",
    "remark": "参数化多条 payload",
  },
  {
    "id": "TC-LOGIN-016",
    "title": "网吧登录-账号密码双字段SQL注入防护",
    "class": "TestSqlInjection",
    "method": "test_sql_injection_in_both_fields_rejected",
    "module": "登录模块",
    "story": "SQL注入防护",
    "priority": "P1",
    "type": "安全测试",
    "precondition": "1. 已打开登录页\n2. 当前 Tab 为「网吧登录」",
    "steps": "1. 账号、密码均输入 SQL 注入 payload\n2. 点击「登录」",
    "expected": "1. 登录失败，仍停留在登录页\n2. 页面不泄露 SQL/数据库错误信息",
    "data": "payload 见 utils/sql_injection_payloads.py",
    "remark": "参数化多条 payload",
  },
  {
    "id": "TC-LOGIN-017",
    "title": "网吧登录-正确账号密码登录成功",
    "class": "TestSuccessfulLogin",
    "method": "test_internet_cafe_login_success",
    "module": "登录模块",
    "story": "正向登录",
    "priority": "P0",
    "type": "正向测试",
    "precondition": "1. 已配置有效网吧账号\n2. 可完成滑块验证（或测试环境免验证）",
    "steps": "1. 打开登录页\n2. 输入网吧账号和密码\n3. 完成滑块验证\n4. 点击「登录」",
    "expected": "1. 登录成功\n2. 离开登录页",
    "data": "账号/密码见 .env：INTERNET_CAFE_ACCOUNT、INTERNET_CAFE_PASSWORD",
    "remark": "默认跳过（@pytest.mark.positive）",
  },
  {
    "id": "TC-LOGIN-018",
    "title": "员工登录-正确账号密码登录成功",
    "class": "TestSuccessfulLogin",
    "method": "test_staff_login_success",
    "module": "登录模块",
    "story": "正向登录",
    "priority": "P0",
    "type": "正向测试",
    "precondition": "1. 已配置有效员工登录账号\n2. 可完成滑块验证",
    "steps": "1. 打开登录页\n2. 切换到员工登录\n3. 输入网吧账号、员工账号、密码\n4. 完成滑块并登录",
    "expected": "1. 登录成功\n2. 离开登录页",
    "data": "见 .env：STAFF_CAFE_ACCOUNT、STAFF_ACCOUNT、STAFF_PASSWORD",
    "remark": "默认跳过",
  },
  {
    "id": "TC-LOGIN-019",
    "title": "代理商登录-正确账号密码登录成功",
    "class": "TestSuccessfulLogin",
    "method": "test_agent_login_success",
    "module": "登录模块",
    "story": "正向登录",
    "priority": "P0",
    "type": "正向测试",
    "precondition": "1. 已配置有效代理商账号\n2. 可完成滑块验证",
    "steps": "1. 打开登录页\n2. 切换到代理商登录\n3. 输入账号密码并登录",
    "expected": "1. 登录成功\n2. 离开登录页",
    "data": "见 .env：AGENT_ACCOUNT、AGENT_PASSWORD",
    "remark": "默认跳过",
  },
]

CASE_BY_ID = {case["id"]: case for case in TEST_CASES}


def allure_display_title(case: dict) -> str:
  return f"{case['id']} {case['title']}"
